#continuous integration for catalog service

name: product-catalog-CI

on:
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout the source code
          uses: actions/checkout@v4

        - name: setup go
          uses: actions/setup-go@v2
          with:
            go-version: 1.22

        - name: build the project
          run: |
                cd src/product-catalog
                go mod download
                go build -o product-catalog-service main.go

        - name: run unit tests
          run: |
                cd src/product-catalog 
                go test ./...

    code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout the source code
          uses: actions/checkout@v4

        - name: run go lint
          run: |
                go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
                golangci-lint run src/product-catalog-service/...
    
    docker:
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Checkout the source code
          uses: actions/checkout@v4

        - name: install docker
          run: docker/setup-buildx-action@v1

        - name: docker login
          run: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }} 
        - name: docker push
          run: docker/build-push-action@v6
          with:
            context: src/product-catalog-service
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
        

    update-k8s:
        runs-on: ubuntu-latest
        needs: docker

        steps:
        - name: Checkout the source code
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.TOKEN }}
        
        - name: update k8s tags in deployment manifest
          run: |
                sed -i 's/image: .*/image:  ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{github.run_id}}/' kubernetes/productcatalog/deploy.yaml
        
        - name: commit the changes
          run: |
                git config --global user.email "lohithdt81@gmail.com"
                git config --global user.name "Lohithdt"
                git add kubernetes/productcatalog/deploy.yaml
                git commit -m "[CI]:update deployment image tag"
                git push 